# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieGuide' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieGuide
  pod 'Alamofire', '~> 3.5.0'
  pod 'AlamofireImage', '~> 2.5'
  pod 'RealmSwift', '0.98.8'

end
